dependencies:
  font_clock:
    url: github.com/toitware/toit-font-clock
    version: ^1.2.0
  max7219:
    path: ..
  pixel_display:
    url: github.com/toitware/toit-pixel-display
    version: ^1.5.0
